/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sports_club;

/**
 *
 * @author dell
 */
public class selection extends javax.swing.JFrame {

    /**
     * Creates new form selection
     */
    public selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel = new javax.swing.JPanel();
        btn_delete = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbtn_employees = new javax.swing.JRadioButton();
        rbtn_members = new javax.swing.JRadioButton();
        rbtn_equipments = new javax.swing.JRadioButton();
        rbtn_events = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(51, 51, 51));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_delete.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 80, 30));

        btn_insert.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 90, 30));

        btn_update.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 100, 30));

        btn_view.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btn_view.setText("View Database");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        jPanel.add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 140, 30));

        btn_reset.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btn_reset.setText("Clear");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("EMPLOYEES DB");
        jPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 170, -1));

        buttonGroup1.add(rbtn_employees);
        rbtn_employees.setText("Employees");
        rbtn_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_employeesActionPerformed(evt);
            }
        });
        jPanel.add(rbtn_employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        buttonGroup1.add(rbtn_members);
        rbtn_members.setText("Members");
        rbtn_members.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_membersActionPerformed(evt);
            }
        });
        jPanel.add(rbtn_members, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        buttonGroup1.add(rbtn_equipments);
        rbtn_equipments.setText("Equipments");
        rbtn_equipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_equipmentsActionPerformed(evt);
            }
        });
        jPanel.add(rbtn_equipments, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        buttonGroup1.add(rbtn_events);
        rbtn_events.setText("Events");
        rbtn_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_eventsActionPerformed(evt);
            }
        });
        jPanel.add(rbtn_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed

      
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        //Show_database();
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        

    }//GEN-LAST:event_btn_resetActionPerformed

    public  void ButtonGroup(){
        buttonGroup1  bg1=new buttonGroup1();
        
        bg1.add(rbtn_employees);
             bg1.add(rbtn_members);
                  bg1.add(rbtn_events);
                       bg1.add(rbtn_equipments);
    }
    
    
    private void rbtn_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_eventsActionPerformed
       
    }//GEN-LAST:event_rbtn_eventsActionPerformed

    private void rbtn_equipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_equipmentsActionPerformed
    
    }//GEN-LAST:event_rbtn_equipmentsActionPerformed

    private void rbtn_membersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_membersActionPerformed
       
    }//GEN-LAST:event_rbtn_membersActionPerformed

    private void rbtn_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_employeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_employeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JRadioButton rbtn_employees;
    private javax.swing.JRadioButton rbtn_equipments;
    private javax.swing.JRadioButton rbtn_events;
    private javax.swing.JRadioButton rbtn_members;
    // End of variables declaration//GEN-END:variables
}
